### ISSUE TITLE
sd-ran deployment

### ISSUE THREAD

**Issue by mzangooei97** [onosproject/ran-simulator#461]
Hi there! 
I tried to deploy the sd-ran chart based on Quick Start instructions, but it failed. I'm quite new to this stuff, so it might be a completely silly mistake! 
Nevertheless, I'm somehow stuck, and appreciate any help! 

This is the error I got:

~/sdran-helm-charts$ helm install sd-ran sd-ran -n sd-ran
Error: found in Chart.yaml, but missing in charts/ directory: nem-monitoring, onos-e2t, onos-a1t, onos-o1t, onos-topo, onos-uenib, onos-config, onos-gui, ran-simulator, onos-cli, onos-kpimon, onos-pci, fb-kpimon-xapp, fb-ah-xapp, fb-ah-gui, onos-mho, onos-rsm, onos-mlb, ah-eson-test-server, onos-exporter

And here's the detail of my workspace:

$ kubectl get nodes
NAME                     STATUS   ROLES                  AGE   VERSION
onos-kubernetes-master   Ready    control-plane,master   29m   v1.23.4
oran-worker              Ready    worker                 27m   v1.23.4

$ kubectl get namespace
NAME              STATUS   AGE
default           Active   28m
kube-node-lease   Active   28m
kube-public       Active   28m
kube-system       Active   28m
micro-onos        Active   20m
sd-ran            Active   8m40s

$ kubectl -n micro-onos get pods
NAME                           READY   STATUS    RESTARTS   AGE
onos-cli-86448f879f-tzw67      1/1     Running   0          19m
onos-config-6546c457fc-h5vwg   6/6     Running   0          19m
onos-consensus-store-0         1/1     Running   0          19m
onos-gui-65f4754c5f-lx5r8      2/2     Running   0          19m
onos-topo-8666cfb4bf-h9tts     3/3     Running   0          19m

$ kubectl -n kube-system get pods
NAME                                              READY   STATUS    RESTARTS      AGE
atomix-controller-68fcf9bf5d-8vj9h                1/1     Running   0             20m
atomix-raft-storage-controller-7f65488ccc-95zdj   1/1     Running   0             20m
coredns-64897985d-ffnwn                           1/1     Running   0             29m
coredns-64897985d-zt6wd                           1/1     Running   0             29m
etcd-onos-kubernetes-master                       1/1     Running   1 (29m ago)   29m
kube-apiserver-onos-kubernetes-master             1/1     Running   0             29m
kube-controller-manager-onos-kubernetes-master    1/1     Running   0             29m
kube-proxy-2njmw                                  1/1     Running   0             29m
kube-proxy-vj8wr                                  1/1     Running   0             27m
kube-scheduler-onos-kubernetes-master             1/1     Running   0             29m
onos-operator-app-69998fd7dc-zwrp6                1/1     Running   0             20m
onos-operator-topo-947b58ffd-ldj7b                1/1     Running   0             20m
weave-net-s2xjs                                   2/2     Running   0             26m
weave-net-wtmcb                                   2/2     Running   0             26m

$ kubectl -n micro-onos get pods
NAME                           READY   STATUS    RESTARTS   AGE
onos-cli-86448f879f-tzw67      1/1     Running   0          19m
onos-config-6546c457fc-h5vwg   6/6     Running   0          19m
onos-consensus-store-0         1/1     Running   0          19m
onos-gui-65f4754c5f-lx5r8      2/2     Running   0          19m
onos-topo-8666cfb4bf-h9tts     3/3     Running   0          19m

**Comment by adibrastegarnia** [comment]
run make deps before deploying it.
