### ISSUE TITLE
ran-simulator locks up with 90+ UEs operating on it

### ISSUE THREAD

**Issue by SeanCondon** [onosproject/ran-simulator#55]
Removing the call to `UpdateTelemetryMetrics()` causes the problem to disappear

**Comment by tomikazi** [comment]
With InfluxDB, the recommend injecting samples in batches. Are we doing that with prometheus? Also, it may be a good idea to do the export off-thread, meaning on another channel to make sure the export does not affect latencies of future requests.

**Comment by SeanCondon** [comment]
this is without Prometheus or InfluxDB - it's just writing to an internal object
